#define VERSION_MAJOR 1
#define VERSION_MINOR 9
#define VERSION_RELEASE 0

#define ONLY_RUSSIAN_LANGUAGE
#define SHOW_ERROR_CODES
#define IGNORE_STYLES_OPTION 1

#ifdef Q_OS_WIN32
 #define REAL_COMPARE_PRECISION 0.0000001
#else
 #define REAL_COMPARE_PRECISION 0
#endif

